server:
  port: 7002

spring:
  application:
    name: customer-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  config:
    import: "configserver:"
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_DEFAULT_ZONE:http://localhost:8761/eureka}

security:
  jwt:
    secret: change_this_secret_in_real_env_min_32_chars

customer:
  seed:
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env
  endpoint:
    health:
      show-details: always

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    root: INFO